@startuml

class Vehicle {
}

class Bicycle {
}

class Motorcycle {
}

class Car {
}

class Sedan {
}

class Coupe {
}

class Minivan {
}

class SportUtilityVehicle {
}

class Truck {
}

class PickupTruck {
}

Vehicle <|-- Bicycle
Vehicle <|-- Motorcycle
Vehicle <|-- Car
Vehicle <|-- Truck
Car <|-- Sedan
Car <|-- Coupe
Car <|-- Minivan
Car <|-- SportUtilityVehicle
Truck <|-- PickupTruck

@enduml
