@startuml

class Person {
}

class Employee {
}

class Student {
}

class Professor {
}

class TeachingAssistant {
}

class Secretary {
}

class DepartmentChair {
}

class Janitor {
}

class SeminarSpeaker {
}

class Course {
}

class Seminar {
}

class Lecture {
}

class ComputerLab {
}

Person <|-- Student
Person <|-- Employee
Person <|-- SeminarSpeaker
Employee <|-- Professor
Employee <|-- TeachingAssistant
Employee <|-- Secretary
Employee <|-- DepartmentChair
Employee <|-- Janitor
Course <|-- Seminar
Course <|-- Lecture

@enduml
